name: development deployment

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-versions: [14.x]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - run: echo "🏃‍♂️ start deploying! "

      - name: Deploy
        run: npm deploy
